(()=>{"use strict";
const KEY="PS_V1000000";
const TEMPLATES={
empty:{name:"Blank",scripts:{'main.ps':'# PlayScript v1000000\nshow "Hello world!"'},entities:[{id:"e1",name:"Player",type:"player",x:120,y:180,w:32,h:32,color:"#7c6cff",speed:180,script:"player.ps"}],scenes:["Main"]},
platformer:{name:"Platformer 2D",scripts:{'main.ps':'show "Platformer online!"\nset score = 0\non start:\n    show "Use arrows / A D to move"\nspawn "Coin" 300 160\nspawn "Coin" 360 120\nspawn "Goal" 700 180','player.ps':'on update:\n    move self with keyboard\non click:\n    add 1 to score\n    show "Score: {score}"'},entities:[{id:"e1",name:"Player",type:"player",x:100,y:210,w:34,h:34,color:"#7c6cff",speed:210,script:"player.ps"},{id:"e2",name:"Ground",type:"platform",x:0,y:270,w:820,h:30,color:"#2a3040"},{id:"e3",name:"Coin",type:"coin",x:300,y:180,w:20,h:20,color:"#facc15",speed:0,script:"main.ps"},{id:"e4",name:"Coin",type:"coin",x:360,y:120,w:20,h:20,color:"#facc15",speed:0,script:"main.ps"},{id:"e5",name:"Goal",type:"goal",x:700,y:210,w:28,h:45,color:"#4ade80",speed:0,script:"main.ps"}],scenes:["Main"]},
topdown:{name:"Top-down Adventure",scripts:{'main.ps':'show "Top-down Adventure"\nset hp = 100\non start:\n    show "Explore the map"\nspawn "NPC" 350 180\nspawn "Chest" 520 130','player.ps':'on update:\n    move self with keyboard\nif hp == 100:\n    show "Healthy!"'},entities:[{id:"e1",name:"Player",type:"player",x:130,y:170,w:30,h:30,color:"#22d3ee",speed:180,script:"player.ps"},{id:"e2",name:"NPC",type:"npc",x:350,y:180,w:30,h:30,color:"#f472b6",speed:0,script:"main.ps"},{id:"e3",name:"Chest",type:"chest",x:520,y:130,w:32,h:24,color:"#f59e0b",speed:0,script:"main.ps"}],scenes:["Main"]},
clicker:{name:"Idle Clicker",scripts:{'main.ps':'set coins = 0\nshow "NEON CLICKER"\nbutton "CLICK" "#7c6cff"\non click:\n    add 1 to coins\n    show "Coins: {coins}"'},entities:[{id:"e1",name:"Core",type:"player",x:360,y:190,w:100,h:100,color:"#7c6cff",speed:0,script:"main.ps"}],scenes:["Main"]},
shooter:{name:"Arcade Arena",scripts:{'main.ps':'set score = 0\nset hp = 100\nshow "ARENA READY"\nspawn "Target" 550 150\nspawn "Target" 680 210\non click:\n    add 10 to score\n    show "Score: {score}"'},entities:[{id:"e1",name:"Player",type:"player",x:100,y:190,w:36,h:36,color:"#fb7185",speed:220,script:"main.ps"},{id:"e2",name:"Target",type:"enemy",x:550,y:150,w:34,h:34,color:"#facc15",speed:0,script:"main.ps"},{id:"e3",name:"Target",type:"enemy",x:680,y:210,w:34,h:34,color:"#facc15",speed:0,script:"main.ps"}],scenes:["Main"]}
};
const DOCS={
syntax:["Sintaxe","A linguagem aceita comandos PlayScript e um estilo Python-like simples.",["Mostrar",'show "Olá!"'],["Bloco indentado",'on start:\n    show "Começando..."'],["Comentário",'# isto é comentário']],
variables:["Variáveis","Variáveis podem guardar números, textos e valores booleanos.",["Criar",'set coins = 100'],["Alterar",'add 10 to coins'],["Interpolar",'show "Coins: {coins}"'],["Condição",'if coins == 110:\n    show "Rich!"']],
game:["Game API","Comandos para entidades e fluxo do jogo.",["Spawn",'spawn "Enemy" 500 180'],["Mover",'move self 120 80'],["Tecla",'move self with keyboard'],["Cena",'scene "Main"']],
ui:["UI","Componentes rápidos para HUD e protótipos.",["Botão",'button "PLAY" "#7c6cff"'],["Texto",'text "Score: {score}"'],["Barra",'progress hp 100 "#22d3ee"'],["Título",'show "GAME OVER"']],
assets:["Assets","Use assets importados dentro do runtime.",["Sprite",'sprite "player.png"'],["Som",'play sound "click.ogg"'],["Imagem",'image "background.png"'],["Dados",'json "config.json"']],
debug:["Debug","Comandos úteis para diagnóstico.",["Log",'debug "valor = {coins}"'],["Assert",'assert coins >= 0 "Coins inválidos"'],["Breakpoint",'breakpoint'],["Teste",'test "Score inicial"']]
};

let S={projects:[],active:null,file:"main.ps",files:{},assets:[],user:"Visitante",builds:0,errors:0,settings:{theme:"midnight",motion:true,sound:true,autosave:true,wrap:true,complete:true,fps:60,debugOverlay:false},history:[],hi:-1};
let R={ctx:null,running:false,keys:{},start:0,raf:0,vars:{},entities:[],logs:[]};

const $=id=>document.getElementById(id), qa=s=>[...document.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,10);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function load(){try{const x=localStorage.getItem(KEY);if(x)S={...S,...JSON.parse(x)}}catch{}if(!S.projects.length)seed();applySettings();renderAll()}
function seed(){const p=makeProject("Neon Adventure","platformer");S.projects=[p];}
function makeProject(name,t){const src=TEMPLATES[t]||TEMPLATES.empty;return{id:uid(),name,template:t,favorite:false,updated:Date.now(),builds:0,scenes:src.scenes.slice(),entities:JSON.parse(JSON.stringify(src.entities)),files:JSON.parse(JSON.stringify(src.scripts)),assets:[],meta:{width:820,height:460,bg:"#0a0f18"}}}
function persist(){localStorage.setItem(KEY,JSON.stringify(S));$("topDirty").classList.add("hidden")}
function touch(){const p=current();if(p)p.updated=Date.now();$("topDirty").classList.remove("hidden");if(S.settings.autosave){clearTimeout(touch.t);touch.t=setTimeout(persist,500)}}
function current(){return S.projects.find(p=>p.id===S.active)}
function toast(msg,type=""){const d=document.createElement("div");d.className="toast "+type;d.textContent=msg;$("toastLayer").appendChild(d);setTimeout(()=>d.remove(),2400)}
function sound(f=600){if(!S.settings.sound)return;try{const AC=AudioContext||webkitAudioContext,a=new AC(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.06);o.stop(a.currentTime+.06)}catch{}}
function modal(id,on=true){$(id).classList.toggle("open",on)}
function nav(view){qa(".view").forEach(v=>v.classList.add("hidden"));$(view).classList.remove("hidden");qa(".nav[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));if(view==="projects")renderProjects();if(view==="assets")renderAssets();if(view==="docs")renderDocs("syntax");if(view==="debug")renderDebug();if(view==="editor")openEditor(S.active);if(view==="home")renderHome();toggleMenu(false)}
function toggleMenu(v){$("sidebar").classList.toggle("active",v);$("overlay").classList.toggle("active",v)}
function bind(){
$("menuBtn").onclick=()=>toggleMenu(true);$("closeMenu").onclick=()=>toggleMenu(false);$("overlay").onclick=()=>toggleMenu(false);
qa(".nav[data-view]").forEach(b=>b.onclick=()=>nav(b.dataset.view));
$("newBtn").onclick=()=>modal("projectModal");$("heroNew").onclick=()=>modal("projectModal");$("newProject2").onclick=()=>modal("projectModal");$("profileBtn").onclick=()=>{ $("profileInput").value=S.user;modal("profileModal")};
qa("[data-close]").forEach(b=>b.onclick=()=>modal(b.closest(".modal").id,false));
$("saveProfileBtn").onclick=()=>{S.user=$("profileInput").value.trim()||"Visitante";$("userName").textContent=S.user;$("avatar").textContent=S.user[0].toUpperCase();persist();modal("profileModal",false);toast("Perfil salvo","ok")};
$("createProjectBtn").onclick=createProject;
$("heroLoad").onclick=()=>nav("projects");$("homeAll").onclick=()=>nav("projects");$("heroDemo").onclick=()=>{openEditor(S.projects[0].id);nav("editor");setTimeout(play,100)};
qa(".quick-list button").forEach(b=>b.onclick=()=>{modal("projectModal");$("templateSelect").value=b.dataset.template});
$("backToProjects").onclick=()=>nav("projects");
$("playBtn").onclick=play;$("playBtn2").onclick=play;$("saveBtn").onclick=save;$("saveBtn2").onclick=save;
$("validateBtn").onclick=validateProject;$("validateBtn2").onclick=validateProject;$("runTestsBtn").onclick=runTests;
$("importAssetBtn").onclick=()=>$("assetInput").click();$("assetInput").onchange=importAssets;
$("importProjectBtn").onclick=()=>$("projectInput").click();$("projectInput").onchange=importProject;
$("exportProjectBtn").onclick=exportProject;$("projectInput").onchange=importProject;
$("newFolderBtn").onclick=()=>toast("Pasta virtual criada (organização por tags na v1000000)");
$("projectSearch").oninput=renderProjects;$("assetSearch").oninput=renderAssets;
$("projectFilter").onclick=e=>{if(e.target.tagName==="BUTTON"){qa("#projectFilter button").forEach(x=>x.classList.remove("active"));e.target.classList.add("active");renderProjects()}};
$("assetFilter").onclick=e=>{if(e.target.tagName==="BUTTON"){qa("#assetFilter button").forEach(x=>x.classList.remove("active"));e.target.classList.add("active");renderAssets()}};
$("addEntityBtn").onclick=addEntity;
qa(".dock-tabs button").forEach(b=>b.onclick=()=>{qa(".dock-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");qa(".dock-panel").forEach(x=>x.classList.add("hidden"));$(b.dataset.dock).classList.remove("hidden");renderDockPanels()});
qa(".bottom-tabs button").forEach(b=>b.onclick=()=>{qa(".bottom-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");qa(".bottom-body").forEach(x=>x.classList.add("hidden"));$(b.dataset.bottom).classList.remove("hidden")});
qa(".file-item").forEach(b=>b.onclick=()=>switchFile(b.dataset.file));
$("codeEditor").addEventListener("input",editorInput);$("codeEditor").addEventListener("keydown",editorKey);$("codeEditor").addEventListener("scroll",syncLines);$("codeEditor").addEventListener("keyup",cursorPos);
$("formatBtn").onclick=format;$("undoBtn").onclick=undo;$("redoBtn").onclick=redo;
$("resetRuntime").onclick=()=>{R.running=false;cancelAnimationFrame(R.raf);play();};$("fullscreenRuntime").onclick=()=>{$("gameViewport").requestFullscreen?.()};
$("findBtn").onclick=()=>{const q=prompt("Buscar no arquivo:");if(q){const i=$("codeEditor").value.indexOf(q);if(i>=0){$("codeEditor").focus();$("codeEditor").setSelectionRange(i,i+q.length)}}};
qa("#docsNav button").forEach(b=>b.onclick=()=>{qa("#docsNav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderDocs(b.dataset.doc)});
$("themeSelect").onchange=e=>{S.settings.theme=e.target.value;applySettings();persist()};$("motionToggle").onchange=e=>{S.settings.motion=e.target.checked;applySettings();persist()};$("soundToggle").onchange=e=>{S.settings.sound=e.target.checked;persist()};$("autosaveToggle").onchange=e=>{S.settings.autosave=e.target.checked;persist()};$("wrapToggle").onchange=e=>{S.settings.wrap=e.target.checked;applySettings();persist()};$("completeToggle").onchange=e=>{S.settings.complete=e.target.checked;persist()};$("fpsSelect").onchange=e=>{S.settings.fps=+e.target.value;persist()};$("debugOverlayToggle").onchange=e=>{S.settings.debugOverlay=e.target.checked;persist();play()};$("clearLocalBtn").onclick=()=>{if(confirm("Apagar todos os projetos e assets locais?")){localStorage.removeItem(KEY);location.reload()}};
window.addEventListener("keydown",globalKeys);window.addEventListener("keyup",e=>R.keys[e.key.toLowerCase()]=false);
$("gameCanvas").addEventListener("pointerdown",()=>{R.keys.mouse=true;executeClickEvents()});
}
function globalKeys(e){if(e.key==="F5"){e.preventDefault();play()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();save()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="n"){e.preventDefault();modal("projectModal")}if(e.key==="Escape")qa(".modal.open").forEach(x=>modal(x.id,false));if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","a","d","w","s"].includes(e.key)){R.keys[e.key.toLowerCase()]=true}}
function createProject(){const name=$("projectName").value.trim()||"Meu Jogo";const t=$("templateSelect").value;const p=makeProject(name,t);S.projects.unshift(p);persist();modal("projectModal",false);$("projectName").value="";openEditor(p.id);nav("editor");toast("Projeto criado","ok")}
function openEditor(id){if(!id)return;S.active=id;const p=current();S.file="main.ps";S.files=p.files;R.entities=JSON.parse(JSON.stringify(p.entities));$("topProjectName").textContent=p.name;$("editorProjectName").textContent=p.name;$("editorProjectMeta").textContent=`Scene: ${p.scenes[0]||"Main"}`;$("codeEditor").value=S.files[S.file]||"";$("activeFileName").textContent=S.file;resetHistory();syncLines();cursorPos();renderDockPanels();renderInspector(null);drawGame();touch()}
function switchFile(file){saveCurrentFile();S.file=file;const p=current();if(!p.files[file])p.files[file]=`# ${file}\n`;$("codeEditor").value=p.files[file];qa(".file-item").forEach(b=>b.classList.toggle("active",b.dataset.file===file));$("activeFileName").textContent=file;resetHistory();syncLines();updateProblems([]);touch()}
function saveCurrentFile(){const p=current();if(p)p.files[S.file]=$("codeEditor").value}
function editorInput(){saveCurrentFile();touch();syncLines();cursorPos();updateOutline();suggest()}
function resetHistory(){S.history=[$("codeEditor").value];S.hi=0}
function snapshot(){const v=$("codeEditor").value;if(S.history[S.hi]!==v){S.history=S.history.slice(0,S.hi+1);S.history.push(v);if(S.history.length>40)S.history.shift();S.hi=S.history.length-1}}
function editorKey(e){if(e.key==="Tab"){e.preventDefault();if(!$("#completion")?.classList.contains("hidden"))insertComplete();else document.execCommand("insertText",false,"  ")}if(e.key==="Enter")setTimeout(()=>{snapshot();syncLines()},0);if(e.key==="Escape")hideComplete()}
function snapshotAlias(){snapshot()}
function syncLines(){const n=$("codeEditor").value.split("\n").length;$("lineNumbers").innerHTML=Array.from({length:n},(_,i)=>i+1).join("<br>");$("lineNumbers").scrollTop=$("codeEditor").scrollTop}
function cursorPos(){const t=$("codeEditor"),s=t.value.slice(0,t.selectionStart),ln=s.split("\n").length,col=s.length-s.lastIndexOf("\n");$("cursorStatus").textContent=`Ln ${ln}, Col ${col}`}
function format(){saveCurrentFile();$("codeEditor").value=$("codeEditor").value.split("\n").map(x=>x.replace(/\s+$/,"")).join("\n").replace(/\n{3,}/g,"\n\n");snapshot();syncLines();touch();toast("Arquivo formatado","ok")}
function undo(){if(S.hi>0){S.hi--;$("codeEditor").value=S.history[S.hi];saveCurrentFile();syncLines();}}
function redo(){if(S.hi<S.history.length-1){S.hi++;$("codeEditor").value=S.history[S.hi];saveCurrentFile();syncLines()}}
function suggest(){if(!S.settings.complete)return;const ed=$("codeEditor"),before=ed.value.slice(0,ed.selectionStart),token=before.split(/\s+/).pop().toLowerCase();if(!token){hideComplete();return}const cmds=["show \"\"","set score = 0","add 1 to score","if score == 10:","loop 5:","spawn \"Enemy\" 500 180","move self with keyboard","on start:","on update:","on click:","button \"PLAY\" \"#7c6cff\"","text \"Hello\"","progress hp 100 \"#22d3ee\"","effect particle \"#a855f7\"","play sound \"click.ogg\"","sprite \"player.png\"","debug \"message\"","assert score >= 0 \"Invalid score\""];const m=cmds.filter(x=>x.toLowerCase().includes(token)).slice(0,8);if(!m.length){hideComplete();return}const box=$("completion");box.innerHTML=m.map((x,i)=>`<div class="complete" data-i="${i}"><span>${esc(x)}</span><b>PS</b></div>`).join("");box.classList.remove("hidden");box.dataset.items=JSON.stringify(m);qa(".complete").forEach(c=>c.onclick=()=>insertComplete(+c.dataset.i))}
function insertComplete(i=0){const box=$("completion");if(box.classList.contains("hidden"))return;let m=[];try{m=JSON.parse(box.dataset.items)}catch{}if(!m.length)return;const ed=$("codeEditor"),pos=ed.selectionStart,before=ed.value.slice(0,pos),token=before.split(/\s+/).pop(),start=pos-token.length;ed.focus();ed.setSelectionRange(start,pos);document.execCommand("insertText",false,m[i]||m[0]);hideComplete();editorInput()}
function hideComplete(){$("completion").classList.add("hidden")}
function updateOutline(){/* reserved for future syntax tree */}
function addEntity(){const p=current();if(!p)return;const n={id:uid(),name:"Entity",type:"npc",x:250+Math.random()*250,y:100+Math.random()*130,w:30,h:30,color:"#22d3ee",speed:0,script:"main.ps"};p.entities.push(n);R.entities=JSON.parse(JSON.stringify(p.entities));renderDockPanels();drawGame();touch();toast("Entidade adicionada","ok")}
function renderDockPanels(){const p=current();if(!p)return;$("entityTree").innerHTML=p.entities.map((e,i)=>`<button class="entity-row" data-id="${e.id}"><span class="e-icon">◈</span><span>${esc(e.name)}</span><span style="margin-left:auto;color:#555">${e.type}</span></button>`).join("");qa(".entity-row").forEach(b=>b.onclick=()=>{renderInspector(b.dataset.id);qa(".entity-row").forEach(x=>x.classList.toggle("active",x.dataset.id===b.dataset.id))});$("sceneFileList").innerHTML=p.scenes.map(s=>`<div class="scene-entry ${s==="Main"?"active":""}">${esc(s)}</div>`).join("");const vars=parseVars(Object.values(p.files).join("\n"));$("varList").innerHTML=Object.entries(vars).map(([k,v])=>`<div class="scene-entry"><b>${esc(k)}</b> <span style="color:#6e7687">${esc(v)}</span></div>`).join("")||`<div class="scene-entry">Nenhuma variável ainda.</div>`}
function renderInspector(id){const p=current();const e=p?.entities.find(x=>x.id===id);if(!e){$("inspectorContent").innerHTML='<div class="empty-inspector">Selecione uma entidade.</div>';return}$("inspectorContent").innerHTML=`<h4>${esc(e.name)} <span style="color:#666">${esc(e.type)}</span></h4><div class="inspector-grid"><label>Name<input id="insName" value="${esc(e.name)}"></label><label>Type<select id="insType"><option>${esc(e.type)}</option><option>player</option><option>enemy</option><option>npc</option><option>coin</option><option>platform</option><option>goal</option></select></label><label>X<input id="insX" type="number" value="${e.x}"></label><label>Y<input id="insY" type="number" value="${e.y}"></label><label>Width<input id="insW" type="number" value="${e.w}"></label><label>Height<input id="insH" type="number" value="${e.h}"></label><label>Color<input id="insColor" value="${esc(e.color)}"></label><label>Speed<input id="insSpeed" type="number" value="${e.speed}"></label></div><div class="inspector-actions"><button class="tiny" id="applyInspector">Aplicar</button><button class="tiny" id="deleteInspector">Excluir</button></div>`;$("applyInspector").onclick=()=>{e.name=$("insName").value;e.type=$("insType").value;e.x=+$("insX").value;e.y=+$("insY").value;e.w=+$("insW").value;e.h=+$("insH").value;e.color=$("insColor").value;e.speed=+$("insSpeed").value;p.entities=R.entities=JSON.parse(JSON.stringify(p.entities));renderDockPanels();drawGame();touch();toast("Entidade atualizada","ok")};$("deleteInspector").onclick=()=>{p.entities=p.entities.filter(x=>x.id!==id);R.entities=JSON.parse(JSON.stringify(p.entities));renderDockPanels();renderInspector(null);drawGame();touch()}}
function parseVars(code){const v={};code.split("\n").forEach(l=>{let m=l.trim().match(/^set\s+(\w+)\s*=\s*(.+)$/);if(m)v[m[1]]=value(m[2],v)});return v}
function value(x,v){x=x.trim();if(/^".*"$/.test(x))return x.slice(1,-1);if(x==="true"||x==="false")return x==="true";if(!isNaN(+x))return +x;return v[x]??x}
function interp(s,v){return String(s).replace(/\{(\w+)\}/g,(_,k)=>v[k]??"undefined")}
function parseStringArg(t,regex){const m=t.match(regex);return m?m[1]:null}

function validateCode(code,file){const errs=[],warn=[];const lines=code.split("\n");lines.forEach((l,i)=>{const t=l.trim();if(!t||t.startsWith("#"))return;
  if(/^if\s+.+:/.test(t)&&!/^if\s+\w+\s*(==|!=|>=|<=|>|<)\s*.+:/.test(t))errs.push(`Linha ${i+1}: condição inválida.`);
  if(/^set\s+\w+\s*=/.test(t)===false && /^(set|add)\b/.test(t) && !/^add\s+-?\d+(?:\.\d+)?\s+to\s+\w+$/.test(t))errs.push(`Linha ${i+1}: atribuição inválida.`);
  if(/^loop\b/.test(t)&&!/loop\s+\d+\s*:/.test(t))errs.push(`Linha ${i+1}: use "loop 5:" por exemplo.`);
  if(/^spawn\b/.test(t)&&!/^spawn\s+"[^"]+"\s+-?\d+(?:\.\d+)?\s+-?\d+(?:\.\d+)?$/.test(t))warn.push(`Linha ${i+1}: spawn esperado: spawn "Enemy" 500 180`);
  if(/^sprite\b/.test(t)&&!/^sprite\s+"[^"]+"\s*$/.test(t))warn.push(`Linha ${i+1}: sprite precisa de um nome de arquivo.`);
});return{errs,warn}}
function validateProject(){const p=current();if(!p){toast("Abra um projeto primeiro","err");return}let allE=[],allW=[];Object.entries(p.files).forEach(([f,c])=>{const r=validateCode(c,f);r.errs.forEach(x=>allE.push(`${f}: ${x}`));r.warn.forEach(x=>allW.push(`${f}: ${x}`))});S.errors+=allE.length;updateProblems(allE,allW);renderDebug();persist();toast(allE.length?`${allE.length} erro(s) encontrado(s)`:`Projeto verificado sem erros críticos` ,allE.length?"err":"ok")}
function updateProblems(errs,warns=[]){$("problemCount").textContent=errs.length;let out=[...errs.map(x=>`<div class="log err">✕ ${esc(x)}</div>`),...warns.map(x=>`<div class="log warn">⚠ ${esc(x)}</div>`)].join("");$("problemsOutput").innerHTML=out||`<div class="log ok">✓ Nenhum problema detectado.</div>`}
function play(){const p=current();if(!p){toast("Crie ou abra um projeto","err");return}saveCurrentFile();const check=validateCode(S.files[S.file],"");if(check.errs.length){updateProblems(check.errs,check.warn);toast("Corrija os erros antes de rodar","err");return}S.builds++;p.builds++;S.errors+=check.errs.length;persist();R.running=true;R.start=performance.now();R.vars=parseVars(Object.values(p.files).join("\n"));R.entities=JSON.parse(JSON.stringify(p.entities));$("runtimeBadge").textContent="● RUNNING";$("runtimeBadge").classList.add("live");$("engineStatus").textContent="● Runtime Running";consoleClear();logConsole(`Build #${S.builds} • ${p.name}`,"ok");executeScriptFile("main.ps");drawGame();cancelAnimationFrame(R.raf);loop();toast("Jogo executado","ok")}
function loop(){if(!R.running)return;updateRuntime();drawGame();R.raf=requestAnimationFrame(loop)}
function updateRuntime(){const dt=1/60;const p=R.entities.find(e=>e.type==="player");if(!p)return;const sp=p.speed*dt;const left=R.keys.arrowleft||R.keys.a,right=R.keys.arrowright||R.keys.d,up=R.keys.arrowup||R.keys.w,down=R.keys.arrowdown||R.keys.s;if(left)p.x-=sp;if(right)p.x+=sp;if(up)p.y-=sp;if(down)p.y+=sp;p.x=Math.max(0,Math.min(current().meta.width-p.w,p.x));p.y=Math.max(0,Math.min(current().meta.height-p.h,p.y));executeUpdateScripts(p)}
function executeUpdateScripts(player){const code=current().files[player.script||"player.ps"];if(!code)return;code.split("\n").forEach(l=>{const t=l.trim();if(t.startsWith("move self with keyboard")){return}else if(t.startsWith("add "))return})}
function executeClickEvents(){const code=Object.values(current().files).join("\n");if(!/on click:/.test(code))return;const m=code.match(/add\s+(\d+(?:\.\d+)?)\s+to\s+(\w+)/);if(m){R.vars[m[2]]=Number(R.vars[m[2]]||0)+Number(m[1])}const msgs=[...code.matchAll(/show\s+"([^"]*)"/g)].map(x=>x[1]);const msg=msgs.at(-1)||"Clicked!";showRuntimeMessage(interp(msg,R.vars));logConsole(`click event • ${interp(msg,R.vars)}`,"ok")}
function executeScriptFile(file){const code=current().files[file]||"";executeLines(code.split("\n"))}
function executeLines(lines){let i=0;while(i<lines.length){let t=lines[i].trim();if(!t||t.startsWith("#")){i++;continue}
  let m;if((m=t.match(/^set\s+(\w+)\s*=\s*(.+)$/))){R.vars[m[1]]=value(m[2],R.vars)}
  else if((m=t.match(/^add\s+(-?\d+(?:\.\d+)?)\s+to\s+(\w+)$/))){R.vars[m[2]]=Number(R.vars[m[2]]||0)+Number(m[1])}
  else if((m=t.match(/^show\s+"([^"]*)"$/))){showRuntimeMessage(interp(m[1],R.vars));logConsole(interp(m[1],R.vars),"ok")}
  else if((m=t.match(/^spawn\s+"([^"]+)"\s+(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)$/))){spawnEntity(m[1],+m[2],+m[3])}
  else if((m=t.match(/^play sound\s+"([^"]+)"$/))){logConsole(`play sound ${m[1]}`);sound(720)}
  else if((m=t.match(/^debug\s+"([^"]*)"$/))){logConsole(interp(m[1],R.vars),"ok")}
  else if((m=t.match(/^if\s+(\w+)\s*(==|!=|>=|<=|>|<)\s*(.+):$/))){let yes=compare(R.vars[m[1]],m[3],m[2]);if(yes&&lines[i+1]?.startsWith("    ")){executeLines([lines[i+1].slice(4)]);i++}}
  else if((m=t.match(/^loop\s+(\d+):$/))){const n=Math.min(100,+m[1]),sub=[];for(let j=i+1;j<lines.length&&lines[j].startsWith("    ");j++)sub.push(lines[j].slice(4));for(let k=0;k<n;k++)executeLines(sub);i+=sub.length}
  else if((m=t.match(/^button\s+"([^"]+)"\s+"([^"]+)"$/))){addRuntimeButton(m[1],m[2])}
  else if((m=t.match(/^progress\s+(\w+)\s+(\d+)\s+"([^"]+)"$/))){showRuntimeHud(m[1],Math.min(100,Math.max(0,+R.vars[m[1]]??+m[2])),m[3])}
  else if(t.startsWith("on ")||t.startsWith("scene ")||t.startsWith("breakpoint")||t.startsWith("assert")){}
  i++}}
function compare(a,b,op){const x=a,y=value(b,R.vars);return op==="=="?String(x)===String(y):op==="!="?String(x)!==String(y):op===">"?x>y:op===">="?x>=y:op==="<"?x<y:x<=y}
function spawnEntity(name,x,y){const p=current(),base=p.entities.find(e=>e.name===name)||{type:name.toLowerCase(),w:28,h:28,color:"#ff66aa",speed:0,script:"main.ps"};R.entities.push({...base,id:uid(),name,x,y});logConsole(`spawn ${name} @ ${x},${y}`,"ok")}
function showRuntimeMessage(msg){$("gameOverlay").innerHTML=`<div class="message">${esc(msg)}</div>`;clearTimeout(showRuntimeMessage.t);showRuntimeMessage.t=setTimeout(()=>{$("gameOverlay").innerHTML="";},1500)}
function addRuntimeButton(text,color){const old=$("gameOverlay").querySelector(".runtimeBtn");if(old)old.remove();const b=document.createElement("button");b.className="runtimeBtn";b.textContent=text;b.style.cssText=`position:absolute;right:12px;bottom:12px;background:${color};border:0;border-radius:7px;padding:8px 12px;color:#fff;font-weight:800;font-size:10px;pointer-events:auto;`;b.onclick=executeClickEvents;$("gameOverlay").appendChild(b)}
function showRuntimeHud(name,val,color){$("gameOverlay").innerHTML=`<div class="hud">${esc(name)} <span style="color:${color}">${esc(val)}</span></div>`}
function drawGame(){const c=$("gameCanvas"),box=$("gameViewport");if(!box)return;c.width=Math.max(1,box.clientWidth*devicePixelRatio);c.height=Math.max(1,box.clientHeight*devicePixelRatio);const x=c.getContext("2d");x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const w=box.clientWidth,h=box.clientHeight;p=current();x.fillStyle=p?.meta.bg||"#0a0f18";x.fillRect(0,0,w,h);const sx=w/(p?.meta.width||820),sy=h/(p?.meta.height||460),scale=Math.min(sx,sy);x.save();x.scale(scale,scale);const cw=p?.meta.width||820,ch=p?.meta.height||460;
  x.fillStyle="#0e1524";x.fillRect(0,0,cw,ch);for(let gx=0;gx<cw;gx+=40){x.strokeStyle="#ffffff08";x.beginPath();x.moveTo(gx,0);x.lineTo(gx,ch);x.stroke()}for(let gy=0;gy<ch;gy+=40){x.strokeStyle="#ffffff08";x.beginPath();x.moveTo(0,gy);x.lineTo(cw,gy);x.stroke()}
  (R.entities.length?R.entities:(p?.entities||[])).forEach(e=>{x.fillStyle=e.color||"#7c6cff";if(e.type==="coin"){x.beginPath();x.arc(e.x+e.w/2,e.y+e.h/2,e.w/2,0,Math.PI*2);x.fill()}else{x.fillRect(e.x,e.y,e.w,e.h)}if(e.name){x.fillStyle="#ffffffaa";x.font="8px JetBrains Mono";x.fillText(e.name,e.x,e.y-4)}});x.restore();
  if(S.settings.debugOverlay){x.fillStyle="#000b";x.fillRect(6,6,190,42);x.fillStyle="#aab2c2";x.font="9px JetBrains Mono";x.fillText(`entities: ${R.entities.length}`,12,20);x.fillText(`vars: ${Object.keys(R.vars).length}`,12,34)}
}
function consoleClear(){$("consoleOutput").innerHTML="";R.logs=[]}
function logConsole(t,type=""){const d=document.createElement("div");d.className=`log ${type}`;d.innerHTML=`<span class="time">[${new Date().toLocaleTimeString()}]</span> ${esc(t)}`;$("consoleOutput").appendChild(d);$("consoleOutput").scrollTop=$("consoleOutput").scrollHeight}
function renderProjects(){const f=q("#projectFilter .active")?.dataset.f||"all",term=($("projectSearch").value||"").toLowerCase();let ps=S.projects.filter(p=>!term||p.name.toLowerCase().includes(term));if(f==="favorite")ps=ps.filter(p=>p.favorite);$("projectGrid").innerHTML=ps.map(p=>`<div class="project-card" data-id="${p.id}"><button class="fav ${p.favorite?"on":""}" data-fav="${p.id}">★</button><h3>${esc(p.name)}</h3><p>${esc(TEMPLATES[p.template]?.name||"Custom project")} • ${p.entities.length} entities • ${Object.keys(p.files).length} scripts</p><div><span class="tag">${p.code||p.id}</span></div><div class="pc-meta"><span>${new Date(p.updated).toLocaleDateString("pt-BR")}</span><span>▶ ${p.builds||0} builds</span></div></div>`).join("")||`<div class="panel">Nenhum projeto encontrado.</div>`;qa(".project-card").forEach(c=>c.onclick=e=>{if(e.target.closest(".fav"))return;openEditor(c.dataset.id);nav("editor")});qa(".fav").forEach(b=>b.onclick=e=>{e.stopPropagation();const p=S.projects.find(x=>x.id===b.dataset.fav);p.favorite=!p.favorite;persist();renderProjects()})}
function renderHome(){$("homeProjects").textContent=S.projects.length;$("homeAssets").textContent=S.assets.length+S.projects.reduce((n,p)=>n+(p.assets?.length||0),0);$("homeScripts").textContent=S.projects.reduce((n,p)=>n+Object.keys(p.files).length,0);$("homeBuilds").textContent=S.builds;$("homeErrors").textContent=S.errors;$("userName").textContent=S.user;$("avatar").textContent=S.user[0].toUpperCase();$("recentGrid").innerHTML=S.projects.slice().sort((a,b)=>b.updated-a.updated).slice(0,3).map(p=>`<div class="recent" data-id="${p.id}"><b>${esc(p.name)}</b><span>${esc(TEMPLATES[p.template]?.name||"Custom")} • ${p.builds} builds</span></div>`).join("");qa(".recent").forEach(c=>c.onclick=()=>{openEditor(c.dataset.id);nav("editor")})}
function renderAssets(){const term=($("assetSearch").value||"").toLowerCase(),f=q("#assetFilter .active")?.dataset.a||"all";let list=S.assets.filter(a=>(!term||a.name.toLowerCase().includes(term))&&(f==="all"||a.kind===f));$("assetGrid").innerHTML=list.map((a,i)=>`<div class="asset-card"><div class="asset-preview">${a.kind==="image"&&a.data?`<img src="${a.data}" alt="">`:a.kind==="audio"?"🔊":a.kind==="data"?"◫":"◈"}</div><h3>${esc(a.name)}</h3><small>${esc(a.kind)} • ${Math.round(a.size/1024)} KB</small><div class="asset-actions"><button class="tiny" onclick="window.useAsset(${i})">Usar</button><button class="tiny" onclick="window.removeAsset(${i})">Excluir</button></div></div>`).join("")||`<div class="panel">Importe sua primeira imagem, música ou arquivo de dados.</div>`}
window.useAsset=i=>{const a=S.assets[i];if(!a)return;openEditor(S.active);nav("editor");setTimeout(()=>{$("codeEditor").focus();$("codeEditor").value+=(($("codeEditor").value.endsWith("\n")?"":"\n")+`sprite "${a.name}"`);editorInput();toast("Asset adicionado ao script","ok")},100)}
window.removeAsset=i=>{S.assets.splice(i,1);persist();renderAssets();renderHome()}
function importAssets(e){[...e.target.files].forEach(file=>{const kind=file.type.startsWith("image/")?"image":file.type.startsWith("audio/")?"audio":"data";const r=new FileReader();r.onload=()=>{S.assets.push({id:uid(),name:file.name,kind,size:file.size,data:kind==="image"?r.result:null});persist();renderAssets();renderHome();toast(`${file.name} importado`,"ok")};if(kind==="image")r.readAsDataURL(file);else r.readAsText(file)});e.target.value=""}
function exportProject(){const p=current();if(!p){toast("Abra um projeto primeiro","err");return}const blob=new Blob([JSON.stringify(p,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=p.name.replace(/\s+/g,"_")+".psproject.json";a.click();URL.revokeObjectURL(a.href);toast("Projeto exportado","ok")}
function importProject(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);p.id=uid();p.updated=Date.now();p.entities=p.entities||[];p.files=p.files||{"main.ps":"# imported"};S.projects.unshift(p);persist();renderProjects();toast("Projeto importado","ok")}catch{toast("JSON de projeto inválido","err")}};r.readAsText(f);e.target.value=""}
function renderDocs(key){const d=DOCS[key];$("docsPage").innerHTML=`<div class="eyebrow">PLAYSCIPT SDK</div><h3>${d[0]}</h3><p>${d[1]}</p>`+d.slice(2).map(x=>`<div class="doc-block"><h4>${esc(x[0])}<button class="copy" data-code="${encodeURIComponent(x[1])}">Copiar</button></h4><pre>${esc(x[1])}</pre></div>`).join("");qa(".copy").forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(decodeURIComponent(b.dataset.code)).then(()=>toast("Comando copiado","ok")))}
function renderDebug(){if(!current())return;const p=current(),tests=[["Sintaxe","Todos os scripts podem ser analisados."],["Entidades","Todos os objetos têm dimensões válidas."],["Assets","Referências podem ser conferidas localmente."],["Variáveis","Variáveis principais podem ser inicializadas."],["Runtime","Canvas e renderer disponíveis."]];$("testList").innerHTML=tests.map((t,i)=>`<div class="test"><div class="icon">✓</div><div><b>${t[0]}</b><span>${t[1]}</span></div></div>`).join("");const r=[];let e=0,w=0;Object.entries(p.files).forEach(([f,c])=>{const x=validateCode(c,f);e+=x.errs.length;w+=x.warn.length;x.errs.forEach(a=>r.push(`<div class="report-item err">✕ ${esc(f)} — ${esc(a)}</div>`));x.warn.forEach(a=>r.push(`<div class="report-item warn">⚠ ${esc(f)} — ${esc(a)}</div>`))});if(!r.length)r.push(`<div class="report-item ok">✓ Nenhum erro crítico encontrado.</div>`);r.push(`<div class="report-item">Scripts: ${Object.keys(p.files).length} • Entidades: ${p.entities.length} • Assets: ${p.assets?.length||0}</div>`);$("debugReport").innerHTML=r.join("")}
function runTests(){validateProject();renderDebug();toast("Suite de testes executada","ok")}
function save(){saveCurrentFile();persist();$("saveState").textContent="Saved";toast("Projeto salvo","ok")}
function saveCurrentFile(){const p=current();if(p)p.files[S.file]=$("codeEditor").value}
function applySettings(){document.body.className=S.settings.theme||"midnight";if(!S.settings.motion)document.body.classList.add("no-motion");$("themeSelect")?.value&&( $("themeSelect").value=S.settings.theme);if($("motionToggle"))$("motionToggle").checked=S.settings.motion!==false;if($("soundToggle"))$("soundToggle").checked=S.settings.sound!==false;if($("autosaveToggle"))$("autosaveToggle").checked=S.settings.autosave!==false;if($("wrapToggle"))$("wrapToggle").checked=S.settings.wrap!==false;if($("completeToggle"))$("completeToggle").checked=S.settings.complete!==false;if($("fpsSelect"))$("fpsSelect").value=String(S.settings.fps||60);if($("debugOverlayToggle"))$("debugOverlayToggle").checked=!!S.settings.debugOverlay}
function renderAll(){renderHome();renderProjects();renderAssets();renderDocs("syntax");if(S.active){$("topProjectName").textContent=current()?.name||"Sem projeto"}}
function bootCanvas(){const c=$("bgCanvas"),x=c.getContext("2d");let a=[];function rs(){c.width=innerWidth;c.height=innerHeight;a=Array.from({length:55},()=>({x:Math.random()*c.width,y:Math.random()*c.height,r:Math.random()*1.6+.3,v:Math.random()*.18+.04}))}rs();addEventListener("resize",rs);(function f(){x.clearRect(0,0,c.width,c.height);x.fillStyle="rgba(120,104,255,.25)";a.forEach(p=>{p.y-=p.v;if(p.y<0)p.y=c.height;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()});requestAnimationFrame(f)})()}
load();bind();bootCanvas();
})();